
# For network analysis
library(tidygraph)
library(igraph)
library(ggraph)
# For everything else
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(lubridate)
library(glue)
library(stringr)
library(fs) # Overwrites `igraph::path`

source(path(here(), "scripts", "utils.R"))

data_dir <- path(here(), "data")
clean_data_path <- path(data_dir, "01-clean-data", "clean_voting_2022_2026.rds")

assert_file_exits(clean_data_path)
clean_votes_2022_2026 <- read_rds(clean_data_path)

# NOTE: Limiting to:
# - Only consider "City Council" comittee (e.g. no sub-comittees)
# - Councillors with `>= 600` votes (out of ~1500 potential votes)
# - Yes or No votes (exludes absents)
city_council_votes <- clean_votes_2022_2026 |>
  filter(committee == "City Council") |>
  filter(n() >= 600, .by = councillor_id) |>
  filter(vote %in% c("No", "Yes"))

# Test Networking --------------------------------------------------------------

nodes <- city_council_votes |> distinct(name = councillor_id)
votes <- city_council_votes |> select(agenda_item_id, councillor_id, vote)

edges <- inner_join(
  votes |> rename(from = councillor_id, from_vote = vote), 
  votes |> rename(to = councillor_id, to_vote = vote),
  by = c("agenda_item_id"),
  relationship = "many-to-many"
) |>
  summarize(
    n_votes = n(), 
    n_agree = sum(from_vote == to_vote),
    .by = c(from, to)
  ) |>
  mutate(agree_perc = n_agree / n_votes)

# This dataset keeps both the A-B and B-A directions, for easier non-directed summaries
agreeableness <- edges |> filter(from != to)

# This dataset only keeps distinct pairs, e.g. A-B or B-A, noting that the order
# doesn't matter (i.e. this is an undirected graph).
edges <- edges |> filter(from < to)

# NOTE: Holyday Stephen is super weird. He votes with the other councillors
#       roughly 50% of the time, regardless of the councillor.
#
# Look at how agree-able each councillor is
agreeableness |>
  group_by(from) |>
  summarize(
    agree_min = min(agree_perc),
    agree_max = max(agree_perc),
    agree_range = abs(agree_max - agree_min),
    agree_mean = mean(agree_perc),
    agree_sd = sd(agree_perc)
  ) |>
  ungroup() |>
  arrange(agree_range) |>
  print(n = 99)

covote_network <- tbl_graph(
  nodes = nodes,
  edges = edges |> select(from, to, weight = agree_perc, n_votes, n_agree),
  directed = FALSE
)

covote_network <- covote_network |>
  activate(nodes) |>
  mutate(
    degree = centrality_degree(weights = weight),
    betweenness = centrality_betweenness(weights = weight, directed = FALSE),
    eigen_centrality = centrality_eigen(weights = weight, directed = FALSE),
    # TODO: Look into `igraph::cluster_louvain` (the backend) and the other 
    # `tidygraph::group_*` options.
    community = group_louvain(
      weights = weight,
      resolution = 1.030 # Default: Lower values typically yield fewer clusters
    ) |> as.factor()
  )

covote_network |> arrange(desc(eigen_centrality))
covote_network |> arrange(desc(betweenness))
covote_network |> arrange(desc(degree))

ggraph(covote_network, layout = "fr") +
  geom_edge_link(aes(alpha = weight, width = weight), colour = "grey60") +
  geom_node_point(aes(colour = community, size = eigen_centrality)) +
  geom_node_label(aes(label = name, colour = community), repel = TRUE, size = 3) +
  scale_edge_width(range = c(0.2, 2)) +
  theme_graph()

# RICE Partisanship Measure ----------------------------------------------------
#
# NOTE: This is generated by Claude, revise later
#
# The cleanest academic framing comes from the DW-NOMINATE tradition (Poole & Rosenthal) 
# in US Congressional voting analysis — the foundational work on recovering latent 
# ideological positions from roll-call votes. Your co-voting network is a simpler, 
# more transparent cousin of that approach. DW-NOMINATE uses ideal point estimation 
# via IRT-style models; your network approach sacrifices some statistical precision 
# but gains interpretability. Worth a sentence acknowledging this lineage.

# For the partisan score specifically, the legislative cohesion literature (Hix, 
#   Noury & Roland is the canonical European Parliament reference)

# Pull node community assignments as a plain tibble for joining
communities <- covote_network |>
  activate(nodes) |>
  as_tibble() |>
  select(councillor_id = name, community)

# For Rice, we need the raw Yes/No counts per bloc per vote
rice_by_vote <- city_council_votes |>
  left_join(communities, by = "councillor_id") |>
  group_by(community, agenda_item_id) |>
  summarise(
    pct_yes = mean(vote == "Yes"),
    pct_no = mean(vote == "No"),
    rice = abs(pct_yes - pct_no), # 1 = unanimous, 0 = perfectly split
    n = n(),
    .groups = "drop"
  )

# Average Rice score per community = cohesion of that bloc
rice_by_community <- rice_by_vote |>
  group_by(community) |>
  summarise(
    rice_mean = mean(rice),
    rice_sd = sd(rice),
    n_votes = n()
  )

# Per-councillor partisan score: how often does this person
# vote with their bloc vs. against it?
councillor_rice <- city_council_votes |>
  filter(vote %in% c("Yes", "No"), councillor_id %in% councillors_to_keep) |>
  left_join(communities, by = "councillor_id") |>
  # For each vote, get the bloc majority position
  left_join(
    rice_by_vote |> select(community, agenda_item_id, pct_yes),
    by = c("community", "agenda_item_id")
  ) |>
  mutate(
    bloc_majority = if_else(pct_yes >= 0.5, "Yes", "No"),
    voted_with_bloc = vote == bloc_majority
  ) |>
  group_by(councillor_id, community) |>
  summarise(
    pct_with_bloc = mean(voted_with_bloc),
    n_votes = n(),
    .groups = "drop"
  )

councillor_rice |>
  arrange(desc(pct_with_bloc)) |>
  print(n = 99)

# Intergroup Validation --------------------------------------------------------

# Validate using the eco-voter measure. If valid, the different communities
# should (might) have different eco-related voting behaviour.

